# Generated by Django 3.1.4 on 2020-12-26 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_rgn', models.CharField(max_length=17)),
                ('desc_rgn', models.TextField()),
                ('img_region', models.ImageField(upload_to='images/regions')),
                ('last_modify', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
