# Generated by Django 3.1.4 on 2020-12-26 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='abbrev_rgn',
            field=models.CharField(default=1, max_length=2),
            preserve_default=False,
        ),
    ]
