# Generated by Django 3.1.4 on 2020-12-26 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0002_region_abbrev_rgn'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_dep', models.CharField(max_length=17)),
                ('desc_dep', models.TextField()),
                ('img_dep', models.ImageField(upload_to='images/departments')),
                ('last_modify_dep', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
