# Generated by Django 3.1.4 on 2020-12-26 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0003_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='region',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='guide.region'),
            preserve_default=False,
        ),
    ]
