# Generated by Django 3.1.4 on 2020-12-26 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0008_arrondissement_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ord', models.CharField(max_length=13)),
                ('abbrv_ord', models.CharField(max_length=4)),
                ('num_ord', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_sch', models.CharField(max_length=17)),
                ('system_sch', models.CharField(max_length=13)),
                ('cycle_complete', models.CharField(max_length=13)),
                ('exit_apee_sch', models.CharField(max_length=3)),
                ('regime_sch', models.CharField(max_length=13)),
                ('zone_sch', models.CharField(max_length=8)),
                ('code_sch', models.CharField(max_length=4)),
                ('desc_sch', models.TextField()),
                ('img_sch', models.ImageField(upload_to='images/schools')),
                ('last_modify_sch', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
