# Generated by Django 3.1.4 on 2020-12-26 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0009_order_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='name_sch',
            field=models.CharField(max_length=31),
        ),
    ]
