# Generated by Django 3.1.4 on 2020-12-27 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0012_auto_20201226_1047'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cycle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ccl', models.CharField(max_length=31)),
                ('desc_ccl', models.TextField()),
                ('img_ccl', models.ImageField(upload_to='images/schools/cycles')),
                ('last_modify_ccl', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edition_year', models.CharField(max_length=10)),
                ('drink_water', models.CharField(max_length=22)),
                ('energy', models.CharField(max_length=13)),
                ('internet', models.CharField(max_length=22)),
                ('regime_sch', models.CharField(max_length=13)),
            ],
        ),
        migrations.AlterField(
            model_name='school',
            name='img_sch',
            field=models.ImageField(upload_to='images/schools'),
        ),
    ]
