# Generated by Django 3.1.4 on 2020-12-27 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0013_auto_20201227_0656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cycle',
            name='img_ccl',
            field=models.ImageField(upload_to='images/cycles'),
        ),
    ]
