# Generated by Django 3.1.4 on 2020-12-27 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0014_auto_20201227_0657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='regime_sch',
        ),
        migrations.AddField(
            model_name='offer',
            name='cycle',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='guide.cycle'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offer',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='guide.school'),
            preserve_default=False,
        ),
    ]
