# Generated by Django 3.1.4 on 2020-12-27 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0015_auto_20201227_0708'),
    ]

    operations = [
        migrations.CreateModel(
            name='Infrastructure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_inf', models.CharField(max_length=62)),
                ('state_inf', models.CharField(max_length=13)),
                ('status_inf', models.CharField(max_length=13)),
                ('abbrv_inf', models.CharField(max_length=7)),
                ('desc_inf', models.TextField()),
                ('img_inf', models.ImageField(upload_to='images/classes')),
                ('last_modify_inf', models.DateTimeField(auto_now=True)),
                ('class_or_inf', models.CharField(max_length=1)),
            ],
        ),
    ]
