# Generated by Django 3.1.4 on 2020-12-27 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0016_infrastructure'),
    ]

    operations = [
        migrations.CreateModel(
            name='LetterAl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_lta', models.CharField(max_length=1)),
                ('num_lta', models.CharField(max_length=2)),
            ],
        ),
    ]
