# Generated by Django 3.1.4 on 2020-12-27 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0017_letteral'),
    ]

    operations = [
        migrations.AddField(
            model_name='infrastructure',
            name='letter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='guide.letteral'),
            preserve_default=False,
        ),
    ]
