# Generated by Django 3.1.4 on 2020-12-27 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0020_infrastructure_school'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_sex', models.CharField(max_length=8)),
                ('char', models.CharField(max_length=1)),
            ],
        ),
    ]
