# Generated by Django 3.1.4 on 2020-12-27 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0021_sex'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_dtl', models.CharField(max_length=9)),
                ('tt_edpp', models.CharField(max_length=2)),
                ('tt_refug', models.CharField(max_length=2)),
                ('tt_ss_acte', models.CharField(max_length=2)),
                ('tt_win', models.CharField(max_length=2)),
                ('tt_abd', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Handicap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_hdp', models.CharField(max_length=9)),
                ('deepness', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='SpecialStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ss', models.CharField(max_length=9)),
                ('factor', models.CharField(max_length=1)),
            ],
        ),
    ]
