# Generated by Django 3.1.4 on 2020-12-27 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0022_detail_handicap_specialstudent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detail',
            name='tt_edpp',
        ),
        migrations.RemoveField(
            model_name='detail',
            name='tt_refug',
        ),
        migrations.RemoveField(
            model_name='detail',
            name='tt_ss_acte',
        ),
        migrations.AddField(
            model_name='detail',
            name='s_std',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='guide.specialstudent'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detail',
            name='sex',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='guide.sex'),
            preserve_default=False,
        ),
    ]
