# Generated by Django 3.1.4 on 2020-12-27 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0023_auto_20201227_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='infrastructure',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='guide.infrastructure'),
            preserve_default=False,
        ),
    ]
