# Generated by Django 3.1.4 on 2020-12-27 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0024_detail_infrastructure'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Handicap',
        ),
        migrations.AddField(
            model_name='detail',
            name='handic_a',
            field=models.CharField(default=0, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detail',
            name='handic_m',
            field=models.CharField(default=0, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detail',
            name='handic_v',
            field=models.CharField(default=0, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detail',
            name='student_sp1',
            field=models.CharField(default=0, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detail',
            name='student_sp2',
            field=models.CharField(default=0, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detail',
            name='student_sp3',
            field=models.CharField(default=0, max_length=2),
            preserve_default=False,
        ),
    ]
