# Generated by Django 3.1.4 on 2020-12-27 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0026_auto_20201227_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='depla',
            field=models.CharField(default=0, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detail',
            name='refug',
            field=models.CharField(default=0, max_length=2),
            preserve_default=False,
        ),
    ]
