# Generated by Django 3.1.4 on 2020-12-27 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0027_auto_20201228_0001'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='ss_acte',
            field=models.CharField(default=0, max_length=2),
            preserve_default=False,
        ),
    ]
