# Generated by Django 3.1.4 on 2020-12-29 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0029_oldclass_personal_statuspsl'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='old',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='guide.oldclass'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personal',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='guide.statuspsl'),
            preserve_default=False,
        ),
    ]
