# Generated by Django 3.1.4 on 2020-12-29 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0032_remove_personal_school'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fonction_psl', models.CharField(max_length=15)),
                ('year_affect', models.CharField(max_length=10)),
                ('year_start_srv', models.CharField(max_length=10)),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guide.personal')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guide.school')),
            ],
        ),
    ]
