# Generated by Django 3.1.4 on 2021-01-02 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0033_appart'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='addr_sch',
            field=models.TextField(default=1, max_length=17),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='school',
            name='altitude_sch',
            field=models.FloatField(default=1, max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='school',
            name='latitude_sch',
            field=models.FloatField(default=1, max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='school',
            name='longitude_sch',
            field=models.FloatField(default=1, max_length=8),
            preserve_default=False,
        ),
    ]
