# Generated by Django 3.1.4 on 2021-01-03 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0034_auto_20210102_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='arrondissement',
            name='latitude_arr',
            field=models.FloatField(default=1, max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='arrondissement',
            name='longitude_arr',
            field=models.FloatField(default=1, max_length=8),
            preserve_default=False,
        ),
    ]
