# Generated by Django 3.1.4 on 2021-01-12 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0035_auto_20210103_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='last_activity',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='personal',
            name='last_modify_pers',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
