# Generated by Django 3.1.4 on 2021-01-21 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0036_auto_20210113_0008'),
    ]

    operations = [
        migrations.CreateModel(
            name='Function',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_func', models.CharField(max_length=15)),
                ('have_off', models.BooleanField()),
                ('last_modify', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
