# Generated by Django 3.1.4 on 2021-01-21 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0037_function'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appart',
            name='fonction_psl',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guide.function'),
        ),
    ]
