# Generated by Django 3.1.4 on 2021-01-21 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0038_auto_20210121_0819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appart',
            name='fonction_psl',
            field=models.CharField(max_length=15),
        ),
        migrations.DeleteModel(
            name='Function',
        ),
    ]
