# Generated by Django 3.1.4 on 2021-01-24 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0040_appart_last_modify_apt'),
    ]

    operations = [
        migrations.AddField(
            model_name='infrastructure',
            name='capacity',
            field=models.IntegerField(default=40, max_length=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='school',
            name='addr_sch',
            field=models.TextField(max_length=53),
        ),
        migrations.AlterField(
            model_name='school',
            name='code_sch',
            field=models.CharField(max_length=12),
        ),
    ]
