# Generated by Django 3.1.4 on 2021-01-25 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0043_auto_20210125_0010'),
    ]

    operations = [
        migrations.AddField(
            model_name='infrastructure',
            name='total_boys',
            field=models.ImageField(default=60, max_length=2, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='infrastructure',
            name='total_girls',
            field=models.ImageField(default=60, max_length=2, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='infrastructure',
            name='total_handic',
            field=models.ImageField(default=10, max_length=2, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='infrastructure',
            name='total_tables',
            field=models.ImageField(default=30, max_length=2, upload_to=''),
            preserve_default=False,
        ),
    ]
