# Generated by Django 3.1.4 on 2021-01-25 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0044_auto_20210125_0353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infrastructure',
            name='total_boys',
            field=models.IntegerField(max_length=2),
        ),
        migrations.AlterField(
            model_name='infrastructure',
            name='total_girls',
            field=models.IntegerField(max_length=2),
        ),
        migrations.AlterField(
            model_name='infrastructure',
            name='total_handic',
            field=models.IntegerField(max_length=2),
        ),
        migrations.AlterField(
            model_name='infrastructure',
            name='total_tables',
            field=models.IntegerField(max_length=2),
        ),
    ]
