# Generated by Django 3.1.4 on 2021-01-26 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0045_auto_20210125_0405'),
    ]

    operations = [
        migrations.AddField(
            model_name='statuspsl',
            name='abr_std',
            field=models.TextField(default='Educateur', max_length=125),
            preserve_default=False,
        ),
    ]
