# Generated by Django 3.1.4 on 2021-01-26 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0046_statuspsl_abr_std'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statuspsl',
            name='abr_std',
        ),
        migrations.AddField(
            model_name='statuspsl',
            name='abr_stp',
            field=models.CharField(default=1, max_length=125),
            preserve_default=False,
        ),
    ]
