# Generated by Django 3.1.4 on 2021-01-27 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0047_auto_20210126_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infrastructure',
            name='capacity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='infrastructure',
            name='total_boys',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='infrastructure',
            name='total_girls',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='infrastructure',
            name='total_handic',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='infrastructure',
            name='total_tables',
            field=models.IntegerField(),
        ),
    ]
