# Generated by Django 3.1.4 on 2021-01-29 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0048_auto_20210127_2239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detail',
            name='birth_paper',
        ),
    ]
